[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[dependencies]
clang = ">=22,<23"
clangdev = ">=22,<23"
clang-tools = ">=22,<23"
glslang = "*"
cmake = "*"
icu = "*"
libcurl = "*"
libjpeg-turbo = "*"
libpng = "*"
libuv = "*"
libwebp = "*"
ninja = "*"
sdl3 = ">=3.4,<4"
pkg-config = "*"
libvulkan-loader = "*"
zlib = "*"

[target.linux-64.dependencies]
mesalib = ">=26.0.3,<27"
sysroot_linux-64 = "*"
vulkan-tools = ">=1.4.341.0,<2"

[target.linux-aarch64.dependencies]
mesalib = ">=26.0.3,<27"
sysroot_linux-aarch64 = "*"
vulkan-tools = ">=1.4.341.0,<2"
