[env]
DYLD_LIBRARY_PATH = "{{config_root}}/../../build"
LD_LIBRARY_PATH = "{{config_root}}/../../build"
PKG_CONFIG = "{{config_root}}/../../.pixi/envs/default/bin/pkg-config"
PKG_CONFIG_PATH = "{{config_root}}/../../build/pkgconfig"
XDG_DATA_DIRS = "{{config_root}}/../../.pixi/envs/default/share:{{env.XDG_DATA_DIRS | default(value=\"/usr/local/share:/usr/share\")}}"

[tasks.build]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build"

[tasks.run]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=owned-texture"

[tasks."run:owned-texture"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=owned-texture"

[tasks."run:borrowed-texture"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=borrowed-texture"

[tasks."run:native-surface"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=native-surface"
