[env]
DYLD_LIBRARY_PATH = "{{config_root}}/../../build"
LD_LIBRARY_PATH = "{{config_root}}/../../build"
PKG_CONFIG = "{{config_root}}/../../.pixi/envs/default/bin/pkg-config"
PKG_CONFIG_PATH = "{{config_root}}/../../build/pkgconfig"
XDG_DATA_DIRS = "{{config_root}}/../../.pixi/envs/default/share"

[tasks.build]
depends = ["//:build", ":compile-shaders"]
run = "zig build"

[tasks.run]
depends = ["//:build", ":compile-shaders"]
run = "zig build run -- --render-target=native-texture"

[tasks."run:native-texture"]
depends = ["//:build", ":compile-shaders"]
run = "zig build run -- --render-target=native-texture"

[tasks."run:shared-texture"]
depends = ["//:build", ":compile-shaders"]
run = "zig build run -- --render-target=shared-texture"

[tasks."run:native-surface"]
depends = ["//:build", ":compile-shaders"]
run = "zig build run -- --render-target=native-surface"
